[Export]
baked_state = false
offer_binder = true
ignore_cache = [
    "index.jl",
]
create_index = false
exclude=[
    # these are in the repo but not used on the website
    "notebooks/introspection.jl",
    "notebooks/04-probability.jl",
    "notebooks/basic_syntax.jl",
    "notebooks/week1/01-fast.jl",
    "notebooks/week3/01-abstraction.jl",
    "notebooks/week3/02-vatiations_fixedpoint.jl",


    # don't run homeworks
    "homework/homework0/hw0.jl",
    "homework/homework0/pizza.jl",
    "homework/homework1/discrete_lockdown.jl",

]


[SliderServer]
exclude=[
    # these are in the repo but not used on the website
    "notebooks/introspection.jl",
    "notebooks/04-probability.jl",
    "notebooks/basic_syntax.jl",
    "notebooks/week1/01-fast.jl",
    "notebooks/week3/01-abstraction.jl",
    "notebooks/week3/02-vatiations_fixedpoint.jl",

    # don't run homeworks
    "homework/homework0/hw0.jl",
    "homework/homework0/pizza.jl",
    "homework/homework1/discrete_lockdown.jl",
]
